
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 16 17:46:55 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREQUAL = 24;
  public static final int LBRACKET = 35;
  public static final int CHAR = 44;
  public static final int CONST = 6;
  public static final int NAMESPACE = 40;
  public static final int LPAREN = 33;
  public static final int GREATER = 23;
  public static final int SEMI = 15;
  public static final int CONTINUE = 12;
  public static final int FOR = 41;
  public static final int LESS = 25;
  public static final int MINUS = 17;
  public static final int RPAREN = 34;
  public static final int AND = 27;
  public static final int LESSEQUAL = 26;
  public static final int DOUBLEPLUS = 39;
  public static final int OR = 28;
  public static final int BOOL = 45;
  public static final int COMMA = 38;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int IF = 9;
  public static final int DOT = 32;
  public static final int NOEQUAL = 22;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int RBRACKET = 36;
  public static final int EQUAL = 30;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int DOUBLEMINUS = 29;
  public static final int MUL = 18;
  public static final int NUMBER = 43;
  public static final int MOD = 20;
  public static final int IDENT = 42;
  public static final int BREAK = 7;
  public static final int VOID = 5;
  public static final int LBRACE = 13;
  public static final int ELSE = 8;
  public static final int READ = 11;
  public static final int DOUBLEEQUAL = 21;
  public static final int RBRACE = 14;
  public static final int PROG = 2;
  public static final int FOLLOWS = 37;
  public static final int PRINT = 3;
  public static final int DOUBLECOLON = 31;
}

